//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CopaDoMundo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jogos
    {
        public int Id_Jogo { get; set; }
        public int Id_Chave { get; set; }
        public int Id_Time1 { get; set; }
        public int SalGols1 { get; set; }
        public int Id_Time2 { get; set; }
        public int SalGols2 { get; set; }
        public bool Empatou { get; set; }
        public int SalPenalteTime1 { get; set; }
        public int SalPenalteTime2 { get; set; }
    
        public virtual Chaves Chaves { get; set; }
        public virtual TimesDaCopa TimesDaCopa { get; set; }
        public virtual TimesDaCopa TimesDaCopa1 { get; set; }
    }
}
